import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallLocalBackwardModels

set_option autoImplicit false

set_option linter.hashCommand false

open PoincareConjecture.M28

open CounterexampleNeckFamily

open CriticalBallBackwardChartData
