import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceTubeFreshSlab
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallFreshSlab
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceFreshSphereIsotopy

set_option autoImplicit false

open PoincareConjecture.M28.SourceTubeData
