import PoincareConjecture.Proofs.M28.Mathlib.CompactPrefixRay
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SelectedInteriorWall
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.InteriorEndpointNeckConfinement
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallRecut
import PoincareConjecture.Proofs.M28.Generalized.StrongNeckCenterCharts
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.Geometry.NormalChartJetBounds
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.RegularSets.CompactImageRegularity
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.RegularSets.LocalIntrinsicDistance
import PoincareConjecture.Proofs.M28.Mathlib.VanishingTailCompletion
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.FixedWallInteriorConfinement
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SelectedNeckVanishingTail
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.Geometry.OpenImageDiffeomorph
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.RegularSets.EuclideanImageBuffer
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SelectedCylinderCompletion
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.FixedWallIntrinsicSegments
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.RegularSets.EuclideanImageDistance

set_option autoImplicit false
