import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceTubeInitialCapture
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceTubeNoncollapse
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.NeckSlabMinimizer

set_option autoImplicit false
set_option linter.hashCommand false
