import PoincareConjecture.Proofs.M28.Sec10_3_Tube.CriticalBallRetainedPath

set_option autoImplicit false
set_option linter.hashCommand false

open PoincareConjecture
open PoincareConjecture.M28
open PoincareConjecture.M28.CounterexampleNeckFamily
