import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallRawStage
import PoincareConjecture.Proofs.M28.Prop9_79_Persistence.NeckGeometry.PartialDiffeomorphPullback
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallInitialGeometry
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceCriticalBallMetricIdentity








set_option autoImplicit false

open PoincareConjecture.M28 PoincareConjecture.M28.CounterexampleNeckFamily
open PoincareConjecture.Proofs.M28.NeckTransfer

