import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceFinalChartDiagonal
import PoincareConjecture.Proofs.M28.Mathlib.RelativeBilinearLimits
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.Geometry.UniformMetricDistance
import PoincareConjecture.Proofs.M28.Mathlib.ConnectedFrontierBarrier
import PoincareConjecture.Proofs.M28.Thm5_6_PartialLimits.Geometry.OpenMetricScaling
import PoincareConjecture.Proofs.M28.Generalized.StrongNeckInverseCenterChart
import PoincareConjecture.Proofs.M28.Generalized.StrongNeckInverseCenterMetric
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceRawStageMetricPairing
import PoincareConjecture.Proofs.M28.Generalized.StrongNeckInverseCenterScalar
import PoincareConjecture.Proofs.M28.Sec10_3_Tube.SourceFinalChartCapture

set_option autoImplicit false
