import PoincareConjecture.Proofs.M54.Mathlib.TopologicalAdapters
import PoincareConjecture.Proofs.Horizon.AlgebraicTopology.FundamentalGroup.PathMaps
import Mathlib.Topology.Homotopy.Contractible
import Mathlib.Topology.Connected.Clopen
