import PoincareConjecture.Proofs.M05.Analysis.ODE.LocalFlow.HigherRegularity.VariationalSuccessorWitness
import PoincareConjecture.Proofs.Horizon.Analysis.ODE.LocalFlow.HigherRegularity.VariationalLevelOneWitness
