import PoincareConjecture.Proofs.M05.Analysis.ODE.LocalFlow.HigherRegularity.VariationalCoproductDerivative
import PoincareConjecture.Proofs.Horizon.Analysis.ODE.LocalFlow.HigherRegularity.VariationalLevelOneSmoothness
