import PoincareConjecture.Proofs.M48.StaticMetric
import PoincareConjecture.Proofs.Horizon.Geometry.RicciFlow.Surgery.Induction.EpochExtension.Analytics.ScalarGradientTransport
import PoincareConjecture.Proofs.Horizon.Geometry.RicciFlow.Surgery.Induction.EpochExtension.Analytics.LaplacianTransport
