import PoincareConjecture.Proofs.M05.Analysis.ODE.LocalFlow.HigherRegularity.VariationalMapContDiffOnK.Foundations
import PoincareConjecture.Proofs.M07.Analysis.ODE.LocalFlow.HigherRegularity.ContDiffOnK
