import PoincareConjecture.Proofs.M12.Geometry.Riemannian.Normalization.Connection.KoszulFunctional
import PoincareConjecture.Proofs.M12.Geometry.Riemannian.Normalization.Connection.Riesz
import PoincareConjecture.Proofs.M01.ConnectionExistenceRegularity


