import PoincareConjecture.Proofs.M05.Analysis.ODE.LocalFlow.HigherRegularity.VariationalOrbitComparison
import PoincareConjecture.Proofs.M07.Analysis.ODE.LocalFlow.HigherRegularity.VariationalMapContDiffOnK
import Mathlib.Analysis.ODE.Gronwall
