import PoincareConjecture.Proofs.M07.Geometry.Riemannian.Coordinates.Exponential.JetBounds.GaussExtension
import PoincareConjecture.Proofs.Horizon.Geometry.Riemannian.Coordinates.Exponential.JetBounds.CoframeEquation
import PoincareConjecture.Proofs.Horizon.Geometry.Riemannian.Metric.LocalExtension
