import PoincareConjecture.Proofs.M35.RawFlow.RotationSymmetry
import PoincareConjecture.Proofs.M35.RawFlow.IntrinsicSpatialMetric
import PoincareConjecture.Proofs.M35.Uniqueness.Heat.SchwartzMixedSmooth
import PoincareConjecture.Proofs.M35.Uniqueness.Heat.PointwiseHeat
import PoincareConjecture.Proofs.M35.Sec12_4_Uniqueness.GaugeRecovery

